### PR TITLE
Adding Updated label with release timestamp

### PR DESCRIPTION
**Pull request by dannyk81**
fixes https://github.com/sstarcher/helm-exporter/issues/3

@sstarcher for your consideration 😄

### CODE REVIEW

**Comment by sstarcher** [comment]
Thanks for the feature

**Comment by mazzy89** [comment]
@dannyk81 it does not work unfortunately for me. I get this:

```
helm_chart_info{chart="metrics-server",namespace="kube-system",release="metrics-server",version="2.5.0"} 1
```

Helm version 2.13.0.

I haven't sat to debug the process though. Just reporting here if you have any quick hint

**Comment by dannyk81** [comment]
@mazzy89 are you building from master? because the code is there and it works fine for me.

**Comment by mazzy89** [comment]
Yes. using the 0.2.0 version from the stable Helm chart.

**Comment by sstarcher** [comment]
I released 0.2.0 10 hours ago.  So you are using the stable chart and you specified specifically 0.2.0 within the last 10 hours?

**Comment by mazzy89** [comment]
Oh make sense. I was running the old version ;-)

**Comment by mazzy89** [comment]
How do you solve guys the problem the updated label in epoch time and its display in Grafana? That number must be multiplied to 1000 before being displayed correctly by Grafana.

**Comment by sstarcher** [comment]
I don't show the time in grafana. Maybe @dannyk81 can answer that.

**Comment by dannyk81** [comment]
I'm actually having issues with this myself, the use of epoch in the label was based on this PR https://github.com/grafana/grafana/pull/14510 in Grafana.

I just looked at the PR and it looks like it assumes the epoch is milliseconds (minimum) while Helm client returns `Seconds`.

@sstarcher I created https://github.com/sstarcher/helm-exporter/pull/10 which just multiplies the Seconds by 1000, let me know what you think, this now works as expected:
image

Note: ensure the `updated` column is set to `Date` type.
image

**Comment by mazzy89** [comment]
Cool. In that way it will work for sure

**Pull request merged**
