### PR TITLE
Fixed connection to namespace

### PR DESCRIPTION
**Pull request by alxrem**
With original code exporter always lists releases in current configured namespace

### CODE REVIEW

**Comment by sstarcher** [comment]
And by that you mean it now does all namespaces vs just a single namespace?  Could you explain what it's doing now vs what it was previously doing?

**Comment by alxrem** [comment]
`actionConfig.Init(..., settings.Namespace(), ...)` fills map `clients` with the same config prepared for namespace $HELM_NAMESPACE (usually ""). Thus code
```
	for _, client := range clients.Items() {
		list := action.NewList(client.(*action.Configuration))
		items, err := list.Run()
```
just as if executes `helm list` on every iteration, so we see only charts installed to the default namespace.

After `actionConfig.Init(..., namespace, ...)` it on every iteration as if execute `helm list -n $namespace`.

**Comment by sstarcher** [comment]
The function connects will connect directly to a single namespace and put the client into an array.  We create a client per namespace.

**Comment by alxrem** [comment]
`actionConfig.Init(..., settings.Namespace(), ...)` creates client connected to namespace where helm_exporter installed.

Steps to reproduce problem:
```
helm repo add sstarcher https://shanestarcher.com/helm-charts/
for NS in alpha beta gamma; do
	kubectl create ns $NS
	helm install -n $NS chart-$NS sstarcher/helm-exporter --set "namespaces=alpha\,beta\,gamma"
done

kubectl -n alpha port-forward deploy/chart-alpha-helm-exporter 9571:9571 & sleep 3 && curl -s localhost:9571/metrics|grep ^helm_

helm_chart_info{appVersion="0.5.0",chart="helm-exporter",namespace="alpha",release="chart-alpha",updated="1582693880000",version="0.5.0"} 1
```
Using `--set "namespaces=alpha\,beta\,gamma"` we expect to see all charts, but exporter installed to the namespace alpha sees only the chart installed to the same namespace.

Try patched exporter:
```
helm upgrade -n alpha chart-alpha sstarcher/helm-exporter --reuse-values --set image.repository=alxrem/helm-exporter
kubectl -n alpha port-forward deploy/chart-alpha-helm-exporter 9572:9571 & sleep 3 && curl -s localhost:9572/metrics|grep ^helm_

helm_chart_info{appVersion="0.5.0",chart="helm-exporter",namespace="alpha",release="chart-alpha",updated="1582693880000",version="0.5.0"} 1
helm_chart_info{appVersion="0.5.0",chart="helm-exporter",namespace="beta",release="chart-beta",updated="1582692018000",version="0.5.0"} 1
helm_chart_info{appVersion="0.5.0",chart="helm-exporter",namespace="gamma",release="chart-gamma",updated="1582692021000",version="0.5.0"} 1
```
Exporter works as expected.

**Comment by sstarcher** [comment]
Wow, I'm so sorry I entirely misread what you had done and thought you were changing it to what it currently is... which as you noticed is terribly wrong.

**Comment by sstarcher** [comment]
Again thank you for the PR and sorry it took so long.  I have updated my notifications for github.

**Pull request merged**
