### PR TITLE
Export latestVersion in metrics which is available in upstream helm repo

### PR DESCRIPTION
**Pull request by blacs30**
The changes introduce the latestVersion label on the metrics. 
The upstream helm repo is check for the latest version. 
It is configurable which upstream repo should be used in case it's not the default. 
In case multiple charts with the same name are found the config can specify the exact one.
The code is basically ported and adjusted from this repository [https://github.com/arminc/k8s-platform-lcm](https://github.com/arminc/k8s-platform-lcm) The credits therefore go to @arminc

_Last remark:_
I'm not absolutely sure if the MIT license would need to be added to this repository and of course whether or not you want this.
According to this thread MIT code and be copied into Apache licensed code [https://law.stackexchange.com/questions/6081/can-i-bundle-mit-licensed-components-in-a-apache-2-0-licensed-project#:~:text=Both%20the%20Apache%20License%20and,licensed%20project%20is%20certainly%20allowed.&text=The%20MIT%20license%20is%20a,license%20you%20can%20think%20of.](https://law.stackexchange.com/questions/6081/can-i-bundle-mit-licensed-components-in-a-apache-2-0-licensed-project#:~:text=Both%20the%20Apache%20License%20and,licensed%20project%20is%20certainly%20allowed.&text=The%20MIT%20license%20is%20a,license%20you%20can%20think%20of.).

### CODE REVIEW

**Comment by sstarcher** [comment]
Thanks these changes are interesting.  I currently have two main questions. 

* Some of this code looks like we could use the helm libraries themselves. 
* Would it make sense to split this out as it's own metric to lower the cardinality of our metrics?

**Comment by blacs30** [comment]
`Some of this code looks like we could use the helm libraries themselves.` -> I don't really have used the helm libraries so you are probably right. 
`Would it make sense to split this out as its own metric to lower the cardinality of our metrics?` -> good point. [https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels](https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels) but would it make a difference to create a separate metric instead having another label? It doesn't right?

**Comment by sstarcher** [comment]
It would greatly reduce the cardinality in a few ways.
* Moving it to a separate metric would allow you to use the latest not as a label, but as a value which would mean the cardinality is 1 vs N(every change to the version)
* Separating it would would also stop us from reducing the carindality of the current metric.  Anytime the version would get updated or any syncs etc you would have yet another increase in cardinality.

Overall not saying that the increase in cardinality is ground breaking, but I think it would make sense to separate it out as the "latest" version is more an object of the chart repo vs the current metrics are metrics of a specific release.

As long as the release metric has the chart name and the latest metric has the chart name label you should be able to link them together if wanted.

**Comment by blacs30** [comment]
`Moving it to a separate metric would allow you to use the latest not as a label, but as a value which would mean the cardinality is 1 vs N(every change to the version)` -> I thought a moment before my previous comment about this but I could'nt get it figured out how I would do that. How can I set a version i.e. `v1.6.4` or even `1.6.4` as a value to a metric. Gauge would be the only type which would come close to but it's just an int64 [gauge godoc](https://godoc.org/github.com/prometheus/client_golang/prometheus#Gauge)

Maybe I'm missing something or overlooking something? Otherwise of course I fully agree with what you wrote.

**Comment by sstarcher** [comment]
Nope, you are correct and I'm mistaken.  As you have pointed out the gain is minimal.  It would be a slight gain as you would not the cardinally of a 8 label metric vs a 1 label metric, but I do agree I doubt that's really something we should consider.

The only thought would be if we would want to separate it out as incase we keep adding extra information.
* release
* chart

**Comment by blacs30** [comment]
It could be a separate for the latestVersion label:
ie.
```text
helm_chart_update{chart="ark",latestVersion="1.2.3"} 0
```

with metric values:
0.0 = no update, 0.5 = error fetching latest version, 1.0 = update available

There could be a mapping between the chart (or should it be the release?) of both metrics. In case one chart is installed multiple times the latest version for that chart is of course the same so it makes sense to have that in as a separate metric but still as a label.

**Comment by blacs30** [comment]
I hope it's okay that I've added all the helm values (helm-doc did it for me). I've just added descriptions.

**Comment by sstarcher** [comment]
Thanks for the contribution!

**Pull request merged**
