### PR TITLE
Add Outdated Metric

### LINKED ISSUE #70: Version outdated label
Hi

Love your project. I was trying to build a new Grafana dashboard based on your metrics and attempted to display the charts, which have an outed version with a special Marking. The problem with that: I can't really perform a proper semver compare in Grafana. So I wanted to ask if it would be possible add a label which indicates, if a version is outdated (latestVersion > version). Basically we could set this to true if the coniditon matches. If not (or if it wasn't able the fetch a latest Version we just set it to false).

What do you think?

### PR DESCRIPTION
**Pull request by oliverbaehler**
Signed-off-by: Oliver Bähler <oliverbaehler@hotmail.com>

Fixes #70 

I have included the Semver library, which gives great functionality. I was also thinking about rewriting versioning.go, but I don't want change too much with one pr. Here one idea how you could simplify the code:

```
//FindHighestVersionInList finds the highest version in an list of versions or returns NOTFOUND
func FindHighestVersionInList(versions []string, allowAllReleases bool) string {
	log.WithField("versions", versions).Debug("FindHighestVersionInList")
	latestVersion := "0.0.0"

	// Create Semver compatible list with all versions
	vs := make([]*semver.Version, len(versions))
	for i, r := range versions {
		v, err := semver.NewVersion(r)
		if err != nil {
			log.WithError(err).WithField("version", r).Fatal("Could not create regexRelease")
		}
		vs[i] = v
	}
	// Sort by latest version
	sort.Sort(semver.Collection(vs))

       ....
}
```

But I will work on that another time. I would highly recommend no longer using the github.com/mcuadros/go-version/ pkg, since it's archived and therefor no longer maintained.

Anyway, if this gets merged, I will also contribute the matching Grafana Dashboard. Sorry if it's a bit messy. I am a new comer to Go.

### CODE REVIEW

**Comment by sstarcher** [comment]
Fully agree with using this semver library over the other one.

**Comment by oliverbaehler** [comment]
@sstarcher  Thanks for your Review. I added Logging for Errors and  moved to Debug (or removed it). Now there's a new metric emitted but only if an semver comparison is true (a release version is outdated). For every other release where the comparison couldn't be made, no metric is emitted. Over the endpoint it looks like this:

```
# TYPE helm_chart_outdated gauge
helm_chart_outdated{appVersion="0.1.0",chart="capsule",latestVersion="0.1.2",namespace="capsule-system",release="capsule",updated="1632921469000",version="0.1.0"} 1
helm_chart_outdated{appVersion="1.6.0",chart="eck-operator-crds",latestVersion="1.8.0",namespace="elastic-system",release="eck-operator-crds",updated="1622021918000",version="1.6.0"} 1
helm_chart_outdated{appVersion="v0.3.5",chart="external-secrets",latestVersion="0.3.6",namespace="external-secrets-system",release="external-secrets",updated="1632918518000",version="0.3.5"} 1
helm_chart_outdated{appVersion="v1.4.1",chart="kyverno",latestVersion="2.1.0",namespace="kyverno-system",release="kyverno",updated="1633449203000",version="v1.4.2"} 1
...
# HELP helm_chart_timestamp Timestamps of helm releases
```

It made sense to me just to emit those which are true. What do you think. Sorry about the mod, my Golang Idea messed around with it I guess.

**Comment by sstarcher** [comment]
ya, I'm not sure if it should always be emitted or just when it's 1.  I would imagine only emitting it when it's one could make it harder to alert on, but I have not touched prometheus in a while.  If it works for your use-case than I'm fine with it.  Do we need all of the labels for helm_chart_outdated?  Maybe just release/namespace as that should be a unique combo?

**Comment by sstarcher** [comment]
Sounds good, can you update the README with the new metric.

**Comment by sstarcher** [comment]
Thank!

**Pull request merged**
